version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  shipnow-api:
    build: .
    container_name: shipnow-api
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mongo

volumes:
  mongo_data:
